created new-yt branch for working on the new features of yt

diff --git a/yt b/yt
--- a/yt
+++ b/yt
@@ -3,8 +3,11 @@
 # Date         : 25th september 2025
 # ================================================================
 # Aim          : A simple script to download Videos or Audio from YouTube using yt-dlp.
-#                The script prompts the user for a Video URL and desired format,
-#                then uses yt-dlp to download the content accordingly.
+#                The script provides options to download video, audio, video clip or audio clip.
+#                It also allows users to choose the quality of download by specifying format codes.
+#                The script is designed to be user-friendly and works in Termux on Android as well
+#                as in Linux environments.
+# Requirements : yt-dlp must be installed and accessible in the system PATH.
 # ================================================================
 
 
@@ -21,6 +24,27 @@ dir_preference=(
 # ===============================================================
 # 1. User-defined functions
 # ===============================================================
+# function for debugging
+show_debugInfo_and_exit() {
+    echo "----------------------------------------"
+    echo "Debug Info:"
+    echo "----------------------------------------"
+    echo "OS                  :  $(uname -a)"
+    echo "User                :  $USER"
+    echo "Current directory   :  $(pwd)"
+    echo "yt-dlp version      :  $(yt-dlp --version)"
+    echo "Downloading from URL:  $URL"
+    echo "Saving download to  :  $FIRST_EXISTING_DIR"
+    echo "choice              :  $CHOICE"
+    echo "Using format code   :  $FORMAT_CODE"
+    echo "Show formats        :  $SHOW_FORMATS"
+    echo "Time-range          :  $time_range"
+    echo "File name pattern   :  $fileName_pattern"
+    echo "----------------------------------------"
+    echo "Full yt-dlp command :  $1"
+    echo "----------------------------------------"
+    exit 0
+}
 # function for colored text output
 color() {
     if [[ "$1" == "red" ]]; then
@@ -46,71 +70,104 @@ handle_exit() {
         exit 0
     fi
 }
+# function to prompt user for format code based on choice
+# download_choice <prompt_help_text> <FORMAT_CODE>
+# e.g. download_choice "[e.g. 18 or 137+140 or bv+ba]" "bv+ba"
+download_choice() {
+    clear
+    echo "$(color green "Your download choice") :  $CHOICE"
+    echo "$(color green "Download Save to")   :  $FIRST_EXISTING_DIR"
+    if [[ "$SHOW_FORMATS" == true ]]; then
+        echo "$(color yellow "fetching download information...")"
+        yt-dlp -F "$URL"
+        [ $? -ne 0 ] && exit 1  # If the above command fails, exit the script
+        echo -e "\n$(color magenta Note:) Type 'exit' in any prompt to quit the script."
+        read -p "$(color magenta "Enter the format code for $CHOICE") $1: " FORMAT_CODE
+        handle_exit "$FORMAT_CODE"
+        # for empty input, set FORMAT_CODE to best available format
+        if [[ -z "$FORMAT_CODE" ]]; then
+            FORMAT_CODE="$2"
+            echo "$(color yellow "No format code entered. Downloading best available quality [format code: $FORMAT_CODE].")"
+        fi
+    else
+        FORMAT_CODE="$2"
+        echo "$(color green "Choosen quality") :  best available quality [format code: $FORMAT_CODE]"
+    fi
+}
 
 # ===============================================================
 # 2. Parsing the CLI arguments
 # ===============================================================
+# printUsage_and_exit <exit_code> <error_message>
 printUsage_and_exit() {
-    echo "Usage: yt <flag> <url> [--]"
-    echo "Examples:"
-    echo '  "yt -v -- https://www.youtube.com/watch?v=example"'
-    echo '  "yt -vc https://www.youtube.com/watch?v=example"'
-    echo '  "yt -ac https://www.youtube.com/watch?v=example --"'
-    echo '  "yt --help"'
-    echo "Flags:"
+    if [[ -n "$2" ]]; then
+        echo "❌Error: $2"
+    fi
+    echo "Usage: yt <flag> <url> [--best] [--debug]"
+    echo -e "\nFlags:"
     echo "  -v,  --video         : Download video"
     echo "  -a,  --audio         : Download audio"
     echo "  -ac, --audio-clip    : Download audio clip"
     echo "  -vc, --video-clip    : Download video clip"
-    echo "  --                   : (Optional) Download best available format directly, without showing format list"
-    echo "  --help              : Show this help message and exit"
+    echo "  --best               : (Optional) Download best available format directly, without showing format list"
+    echo "  --debug              : (Optional) instead of downloading, show debug info and full yt-dlp command"
+    echo "  --help               : Show this help message and exit"
+    echo -e "\nExamples:"
+    echo '  "yt -v --best https://www.youtube.com/watch?v=example"'
+    echo '  "yt -v --best https://www.youtube.com/watch?v=example --debug"'
+    echo '  "yt -vc https://www.youtube.com/watch?v=example"'
+    echo '  "yt -ac https://www.youtube.com/watch?v=example --"'
+    echo '  "yt --help"'
     exit "$1"
 }
 # Default values
-choice="NA"
-show_help=false
-show_formats=true
-url="NA"
+CHOICE="NA"
+SHOW_HELP=false
+SHOW_FORMATS=true
+URL="NA"
+DEBUG_MODE=false
 for arg in "$@"; do     # Iterate over all CLI arguments
     case "$arg" in
         -v|--video)
-            choice="video"
+            CHOICE="video"
             ;;
         -a|--audio)
-            choice="audio"
+            CHOICE="audio"
             ;;
         -vc|--video-clip)
-            choice="video-clip"
+            CHOICE="video-clip"
             ;;
         -ac|--audio-clip)
-            choice="audio-clip"
+            CHOICE="audio-clip"
             ;;
         --help)
-            show_help=true
+            SHOW_HELP=true
             ;;
-        --)
-            show_formats=false
+        --best)
+            SHOW_FORMATS=false
             ;;
         http://*|https://*)
-            url="$arg"
+            URL="$arg"
+            ;;
+        --debug)
+            DEBUG_MODE=true
             ;;
         *)
-            echo "❌ Parsing Error: $(color red "$arg") is not a valid argument."
-            printUsage_and_exit 1
+            printUsage_and_exit 1 "Unknown option $(color red "$arg")"
             ;;
     esac
 done
 # Check if required arguments are provided otherwise show usage and exit
-if [[ "$show_help" == true ]]; then
-    if [[ "$choice" != "NA" || "$url" != "NA" || "$show_formats" == false ]]; then
-        echo "❌ Error: $(color red "--help") cannot be combined with other arguments."
-        printUsage_and_exit 1
-    else
+if [[ "$SHOW_HELP" == true ]]; then
+    # Ensure --help is only used alone e.g. "yt --help"
+    if [[ $# -eq 1 && "$1" == "--help" ]]; then
         printUsage_and_exit 0
+    else
+        printUsage_and_exit 1 "$(color red "--help") cannot be combined with other arguments."
     fi
-elif [[ "$choice" == "NA" || "$url" == "NA" ]]; then
-    echo "❌ Error: Both <flag> and <url> are required arguments."
-    printUsage_and_exit 1
+# CHOICE and URL are required arguments
+elif [[ "$CHOICE" == "NA" || "$URL" == "NA" ]]; then
+    printUsage_and_exit 1 "Both $(color red "<flag>") and $(color red "<url>") are required arguments."
 fi
 
 # ===============================================================
@@ -118,8 +175,8 @@ fi
 # ===============================================================
 
 # step 1: Exit the script if yt-dlp is not installed
-if ! command -v yt-dlp &> /dev/null; then
-    echo "❌ yt-dlp is not installed. Please install it first."
+if ! command -v yt-dlp >/dev/null 2>&1; then
+    echo "❌Error: yt-dlp is not installed. Please install it first."
     exit 1
 fi
 
@@ -133,92 +190,59 @@ for dir in "${dir_preference[@]}"; do
 done
 # Exit the script if no directory exists
 if [ -z "$FIRST_EXISTING_DIR" ]; then
-    echo "❌ None of the directories exist to save downloads."
+    echo "❌Error: None of the directories exist to save downloads."
     echo "Please modify the script $(color yellow "$MYCMD/yt") to include an existing directory."
     exit 1
 fi
 cd "$FIRST_EXISTING_DIR"
 
 # step 3: Starting download based on user inputs
-# till here, parsing of arguments is done and have valid user inputs ($choice and $url or $show_formats)
-if [[ "$choice" == "video" ]]; then
-    fileName_pattern="%(title)s_%(id)s_%(resolution)s"     # Pattern for naming of downloaded files
-    clear
-    echo "$(color green "Your download choice") :  $choice"
-    if [[ "$show_formats" == true ]]; then
-        echo "$(color yellow "fetching download information...")"
-        yt-dlp -F "$url"
-        [ $? -ne 0 ] && exit 1  # If the above command fails, exit the script
-        echo -e "\n$(color magenta Note:) Type 'exit' in any prompt to quit the script."
-        read -p "$(color magenta "Enter the format code for Video (e.g. 18 or 137+140 or bv+ba):") " format_code
-        handle_exit "$format_code"
-        # for empty input, set format_code to best available format
-        if [[ -z "$format_code" ]]; then
-            format_code="bv+ba"
-            echo "$(color yellow "No format code entered. Downloading best video + best audio (bv+ba).")"
-        fi
-    else
-        format_code="bv+ba"
-        echo "$(color green "Choosen quality") :  best audio + best video (bv+ba)"
-    fi
+# till here, parsing of arguments is done and have valid user inputs ($CHOICE and $URL or $SHOW_FORMATS)
+fileName_pattern="%(title)s_%(id)s_%(resolution)s"     # Pattern for naming of downloaded files
 
-    # remove after debugging
-    echo "----------------------------------------"
-    echo "Debug Info:"
-    echo "Downloading from URL :  $url"
-    echo "choice            :  $choice"
-    echo "Using format code   :  $format_code"
-    echo "Saving to directory  :  $FIRST_EXISTING_DIR"
-    echo "File name pattern   :  $fileName_pattern"
-    echo "----------------------------------------"
-    exit 0
-    # End of remove after debugging
+if [[ "$CHOICE" == "video" ]]; then
+    download_choice "$(color green "[e.g. 18 or 137+140 or bv+ba]")" "bv+ba"
+    echo "helo"
+    show_debugInfo_and_exit
 
     # yt-dlp command to download Video
     yt-dlp \
-    -f "$format_code" \
+    -f "$FORMAT_CODE" \
     -o "$fileName_pattern" \
     --merge-output-format mp4 \
     --embed-thumbnail \
     --no-playlist \
     --retries infinite \
     --fragment-retries 10 \
-    "$url"
+    "$URL"
 # ===============================================================
 
-elif [[ "$choice" == "audio" ]]; then
-    read -p "$(color magenta "Enter the format code for Audio (e.g. 140 or ba):") " format_code
-    handle_exit "$format_code"
-    # If the user entered an empty format code, download the best available format
-    if [[ -z "$format_code" ]]; then
-        format_code="ba"  # Best audio
-        echo "$(color yellow "No format code entered. Defaulting to best audio (ba).")"
-    fi
+elif [[ "$CHOICE" == "audio" ]]; then
+    download_choice "[e.g. 140 or ba]" "ba"
+    show_debugInfo_and_exit
+
     # yt-dlp command to download Audio
     yt-dlp \
-    -f "$format_code" \
+    -f "$FORMAT_CODE" \
     -o "$fileName_pattern" \
     --extract-audio \
     --embed-thumbnail \
     --no-playlist \
     --retries infinite \
     --fragment-retries 10 \
-    "$url"
+    "$URL"
 # ===============================================================
 
-elif [[ "$choice" == "video-clip" ]]; then
-    read -p "$(color magenta "Enter the clip timing range (e.g., 00:01:30-00:02:45):") " time_range
+elif [[ "$CHOICE" == "video-clip" ]]; then
+    echo -e "\n$(color magenta Note:) Type 'exit' in any prompt to quit the script."
+    read -p "$(color magenta "Enter the $CHOICE timing range [e.g. 00:01:30-00:02:45]: ")" time_range
     handle_exit "$time_range"
-    read -p "$(color magenta "Enter the format code for Video (e.g. 18 or 137+140 or bv+ba):") " format_code
-    handle_exit "$format_code"
-    # If the user entered an empty format code, download the best available format
-    if [[ -z "$format_code" ]]; then
-        format_code="bv+ba"  # Best video + best audio
-        echo "$(color yellow "No format code entered. Defaulting to best video + best audio (bv+ba).")"
-    fi
+    download_choice "[e.g. 18 or 137+140 or bv+ba]" "bv+ba"
+    show_debugInfo_and_exit
+
     # yt-dlp command to download Video clips
     yt-dlp \
-    -f "$format_code" \
+    -f "$FORMAT_CODE" \
     -o "$fileName_pattern" \
     --merge-output-format mp4 \
     --download-sections "*$time_range" \
@@ -227,22 +251,19 @@ elif [[ "$choice" == "video-clip" ]]; then
     --no-playlist \
     --retries infinite \
     --fragment-retries 10 \
-    "$url"
+    "$URL"
 # ===============================================================
 
-elif [[ "$choice" == "audio-clip" ]]; then
-    read -p "$(color magenta "Enter the clip timing range (e.g., 00:01:30-00:02:45):") " time_range
+elif [[ "$CHOICE" == "audio-clip" ]]; then
+    echo -e "\n$(color magenta Note:) Type 'exit' in any prompt to quit the script."
+    read -p "$(color magenta "Enter the $CHOICE timing range [e.g. 00:01:30-00:02:45]: ")" time_range
     handle_exit "$time_range"
-    read -p "$(color magenta "Enter the format code for Audio (e.g. 140 or ba):") " format_code
-    handle_exit "$format_code"
-    # If the user entered an empty format code, download the best available format
-    if [[ -z "$format_code" ]]; then
-        format_code="ba"  # Best audio
-        echo "$(color yellow "No format code entered. Defaulting to best audio (ba).")"
-    fi
+    download_choice "[e.g. 140 or ba]" "ba"
+    show_debugInfo_and_exit
+
     # yt-dlp command to download Audio clips
     yt-dlp \
-    -f "$format_code" \
+    -f "$FORMAT_CODE" \
     -o "$fileName_pattern.mp3" \
     --extract-audio \
     --download-sections "*$time_range" \
@@ -251,6 +272,6 @@ elif [[ "$choice" == "audio-clip" ]]; then
     --no-playlist \
     --retries infinite \
     --fragment-retries 10 \
-    "$url"
+    "$URL"
 # ===============================================================
 fi
